### ISSUE TITLE
Top XY position of selection window

### ISSUE THREAD

**Issue by Ahmad19860** [zhouray/SelectableTextView#2]
Hi,
This is really a great effort. I was struggling with text selection and I got this source.
Now in this i want to show a popup window at top of the selection window but not getting the exact position. Please suggest your help. I am attaching the screens that will explain my query. Issue occurs when I scroll the handles to select more text.
1.png-> showing what I want
2.png _> showing what I am getting.

![1](https://cloud.githubusercontent.com/assets/10357200/6640796/a3d1e6f2-c9bf-11e4-9033-f1a71227f1f2.png)
![2](https://cloud.githubusercontent.com/assets/10357200/6640794/a2d92fda-c9bf-11e4-9f7c-4a46486c74f0.png)

**Comment by zhouray** [comment]
Hi,
Sorry I'm very busy at the moment so I don't have time to take a look at this now. :(
But I've made some updates to the SelectableTextView on my other project (that might fixes your problem). It's at https://bitbucket.org/rayzhou/jaderead-restart . It's called JTextView in src/com/zyz/mobile/widget/JTextView.java
Please try that first and see if it solves your problem. Let me know how it goes.
Ray
Date: Fri, 13 Mar 2015 08:05:01 -0700

**Comment by Ahmad19860** [comment]
Hi zhouray,
Thanks to reply. I tried with JTextView and it worked for me as desired.
